import jsPDF from 'jspdf';

export const createSamplePDF = () => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('NGO Resource Guide', 20, 30);
  
  // Subtitle
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text('Comprehensive Guide for Non-Profit Organizations', 20, 45);
  
  // Content sections
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('1. Introduction', 20, 70);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const introText = `This document provides essential resources and guidelines for NGO management.
It covers best practices, templates, and tools to help organizations achieve
their mission effectively.`;
  
  const splitIntro = doc.splitTextToSize(introText, 170);
  doc.text(splitIntro, 20, 85);
  
  // Section 2
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('2. Key Resources', 20, 120);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const resourcesText = `• Grant Application Templates
• Impact Measurement Frameworks
• Volunteer Management Systems
• Fundraising Strategy Guides
• Financial Management Tools
• Social Media Marketing Kits`;
  
  const splitResources = doc.splitTextToSize(resourcesText, 170);
  doc.text(splitResources, 20, 135);
  
  // Section 3
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('3. Best Practices', 20, 200);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const practicesText = `1. Maintain transparent financial records
2. Engage stakeholders regularly
3. Measure and report impact consistently
4. Build strong partnerships
5. Invest in staff development
6. Use technology effectively`;
  
  const splitPractices = doc.splitTextToSize(practicesText, 170);
  doc.text(splitPractices, 20, 215);
  
  // Footer
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by NGO Resource Platform - January 2025', 20, 280);
  
  return doc;
};

export const downloadSamplePDF = () => {
  const doc = createSamplePDF();
  doc.save('ngo-resource-guide.pdf');
};

export const getSamplePDFBlob = () => {
  const doc = createSamplePDF();
  return doc.output('blob');
};